### ISSUE TITLE
EPG Missing In  TATAPLAY 2 DAYS EPG GUIDE

### ISSUE THREAD

**Issue by iamsandeepnegi** [mitthu786/tvepg#2]
EPG Missing In  TATAPLAY 2 DAYS EPG GUIDE, I think channel id is different in name section (snehts306) from channel id in program guide (ts306) is the reason behind this.

**Comment by mitthu786** [comment]
ok now fixed

**Comment by iamsandeepnegi** [comment]
Still not changed

</channel>
 <channel id=**"snehts306">**
  <display-name>
   Comedy Central

</programme>
 <programme channel="**ts306**" start="20220925184500 +0530" stop="20220925190500 +0530">
  <title lang="en">

**Comment by iamsandeepnegi** [comment]
Still not changed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by iamsandeepnegi** [comment]
yeah, now its working!
Thanks

**Comment by iamsandeepnegi** [comment]
one more issue now coming time shift in EPG. Its showing +0530, change it to 0000.

[
![time](https://user-images.githubusercontent.com/91105635/192434398-e02b885e-2b7a-4126-9ce5-a0861d341bdd.jpg)
](url)

**Comment by mitthu786** [comment]
It's not an issue. For the Indian region +0530 is used.

> one more issue now coming time shift in EPG. Its showing +0530, change it to 0000.
> 
> [ ![time](https://user-images.githubusercontent.com/91105635/192434398-e02b885e-2b7a-4126-9ce5-a0861d341bdd.jpg) ](url)

**Comment by iamsandeepnegi** [comment]
I am checking epg in Indian region also. 
Its showing epg with +5.30 Hrs shift difference.
you can also check the same in actual epg showing in tivimate/ott navigator.

**Comment by iamsandeepnegi** [comment]
Check Jio EPG its with +0000 and its showing correct EPG in Indian region.
<img width="951" alt="JIo" src="https://user-images.githubusercontent.com/91105635/192435934-527704ef-89eb-466d-9d73-fb42f49756c1.png">

**Comment by mitthu786** [comment]
> I am checking epg in Indian region also. Its showing epg with +5.30 Hrs shift difference. you can also check the same in actual epg showing in tivimate/ott navigator.

Okk as ur wish

**Comment by iamsandeepnegi** [comment]
Thanks for being so active!
You can confirm this by others, I think time shift of +0000 can solve this issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iamsandeepnegi** [comment]
Everything Working fine now.
Thanks!

**Comment by iamsandeepnegi** [comment]
Yeah, now its working!
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
