### ISSUE TITLE
Can't connect with given URL

### ISSUE THREAD

**Issue by pranv12** [mitthu786/tvepg#9]
I tried using all URLs in OTT navigator app. But it following error occured.

`>3avkb.short.gy..`
`3 avkb.short.gy...ERR`
`3 avkb.short.gy....ERR... Live channels`
`contains no supported live channels. Check username/`
`key/password/url.`
`[Sep 01, 21:32] Configuration error. Failed to load data`
`The configured provider or playlist cannot be reached.`
`Please re-check the provider settings and if they seems`
`OK, contact your IPTV provider.`

Help me with this. Thank you.
Also a step by step guide would be appreciated :)

**Comment by mitthu786** [comment]
It's not a live TV playlist. It's an EPG.
